@host = https://listasnegras.herokuapp.com/

@reniec = https://app-reniec.herokuapp.com/

https://equifax-gnaranja-22.herokuapp.com/api/consulta/

@pasarela = https://app-reniec.herokuapp.com/
https://equifax-gnaranja-22.herokuapp.com/api/consulta

GET {{pasarela}}/api/consulta HTTP/1.1
Accept: application/json


GET {{reniec}}/api/persona/ HTTP/1.1
Accept: application/json



GET {{host}}/api/clientes/ HTTP/1.1
Accept: application/json


POST {{host}}/api/clientes/ HTTP/1.1
Content-Type:application/json

{
    "DNI": 23456712,
    "Nombre": "Bruno",
    "Apellidos": "Picaso",
    "CalifSBS": "Mala Calificacion",
    "precio": 67.00,
    "status": "ACTIVO"
}

POST {{host}}/api/clientes/ HTTP/1.1
Content-Type:application/json

{
    "precio": 65.00,
    "status": null,
    "nombre": "Bruno",
    "apellidos": "Picaso",
    "califSBS": "Mala Calificacion",
    "dni": 23456712
}